steps:
  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fluxo-barcode:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/fluxo-barcode:latest', '.']
  
  # Push para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fluxo-barcode:$SHORT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fluxo-barcode:latest']
  
  # Deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fluxo-barcode'
      - '--image=gcr.io/$PROJECT_ID/fluxo-barcode:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=300'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'
      # Adicione outras variáveis de ambiente aqui ou configure no Console
      # --set-env-vars=PGHOST=seu-host,PGDATABASE=seu-db,PGUSER=seu-user,PGPASSWORD=sua-senha

images:
  - 'gcr.io/$PROJECT_ID/fluxo-barcode:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/fluxo-barcode:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

